# reference: http://www.objc.io/issue-6/travis-ci.html

# whitelist
branches:
  only:
    - master
language: objective-c
os: osx
osx_image: xcode7
env:
    matrix:
    - TEST_SDK=iphonesimulator7.1
    - TEST_SDK=iphonesimulator8.1
    - TEST_SDK=iphonesimulator9.0
script:
- xctool test -test-sdk $TEST_SDK -workspace Example/PINRemoteImage.xcworkspace -scheme PINRemoteImage ONLY_ACTIVE_ARCH=NO
